# Generated by Django 5.2.7 on 2025-10-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleverse',
            name='verse',
            field=models.CharField(max_length=100),
        ),
    ]
