# Generated by Django 5.2.7 on 2025-10-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_alter_readingprogress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='message',
            field=models.CharField(default='Time to read your Bible! 🙏', max_length=255),
        ),
    ]
